import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';
import { MealPlan } from '../../../types/meal'; // Corrected path to shared type

// Register a font (optional, but good for consistency/style)
// Using a standard font like Helvetica for broad compatibility
// Font.register({ family: 'Helvetica', src: 'path-to-helvetica.ttf' }); // Example if embedding

// Define styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 30,
    fontFamily: 'Helvetica', // Use registered or default font
  },
  header: {
    fontSize: 24,
    marginBottom: 20,
    textAlign: 'center',
    color: '#333333',
    fontWeight: 'bold',
  },
  daySection: {
    marginBottom: 25,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
    paddingBottom: 15,
  },
  dayHeader: {
    fontSize: 18,
    marginBottom: 15,
    color: '#444444',
    fontWeight: 'bold',
  },
  mealSection: {
    marginBottom: 10,
    paddingLeft: 10,
  },
  mealTitle: {
    fontSize: 14,
    marginBottom: 5,
    fontWeight: 'bold',
    color: '#555555',
  },
  mealDetails: {
    fontSize: 11,
    marginBottom: 8,
    color: '#666666',
  },
  ingredientsHeader: {
      fontSize: 12,
      fontWeight: 'bold',
      marginTop: 5,
      marginBottom: 3,
      color: '#666666',
  },
  ingredientItem: {
    fontSize: 10,
    marginLeft: 10,
    marginBottom: 2,
    color: '#777777',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    color: 'grey',
    fontSize: 10,
  },
});

interface MealPlanPDFProps {
  mealPlan: MealPlan;
}

// Create Document Component
const MealPlanPDF: React.FC<MealPlanPDFProps> = ({ mealPlan }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View>
        <Text style={styles.header}>Your Weekly Meal Plan</Text>
      </View>

      {mealPlan.days.map((day, dayIndex) => (
        <View key={dayIndex} style={styles.daySection}>
          <Text style={styles.dayHeader}>Day {day.day}</Text>
          {day.meals.map((meal, mealIndex) => (
            <View key={mealIndex} style={styles.mealSection}>
              <Text style={styles.mealTitle}>{meal.name}</Text>
              <Text style={styles.mealDetails}>Type: {meal.type} | Est. Time: {meal.estimated_time} mins</Text>
              <Text style={styles.ingredientsHeader}>Ingredients:</Text>
              {meal.ingredients.map((ingredient, ingIndex) => (
                <Text key={ingIndex} style={styles.ingredientItem}>- {ingredient}</Text>
              ))}
            </View>
          ))}
        </View>
      ))}

       <Text style={styles.footer}>Generated by DontGetFat App</Text>
    </Page>
  </Document>
);

export default MealPlanPDF;
